//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project2FreelancerPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class freelancertab
    {
        public int userid { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string skill { get; set; }
        public int experience { get; set; }
        public string resume { get; set; }
        public string photo { get; set; }
        public string status { get; set; }
    }
}
