//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project2FreelancerPortal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class freelanceDbEntities : DbContext
    {
        public freelanceDbEntities()
            : base("name=freelanceDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminReg> adminRegs { get; set; }
        public virtual DbSet<freelancertab> freelancertabs { get; set; }
        public virtual DbSet<logintab> logintabs { get; set; }
        public virtual DbSet<project_tab> project_tab { get; set; }
        public virtual DbSet<proposal> proposals { get; set; }
        public virtual DbSet<skill> skills { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_GetId(string una, string pw)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_GetId", unaParameter, pwParameter);
        }
    
        public virtual ObjectResult<string> sp_GetLogtype(string una, string pw)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GetLogtype", unaParameter, pwParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_LoginDb(string una, string pw)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_LoginDb", unaParameter, pwParameter);
        }
    
        public virtual int sp_LoginInsert(Nullable<int> rid, string una, string pw, string type)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LoginInsert", ridParameter, unaParameter, pwParameter, typeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MaxLogId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MaxLogId");
        }
    
        public virtual int sp_registerAdmin(Nullable<int> id, string name, string em, string ph)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emParameter = em != null ?
                new ObjectParameter("em", em) :
                new ObjectParameter("em", typeof(string));
    
            var phParameter = ph != null ?
                new ObjectParameter("ph", ph) :
                new ObjectParameter("ph", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_registerAdmin", idParameter, nameParameter, emParameter, phParameter);
        }
    
        public virtual int sp_registerUser(Nullable<int> id, string name, string em, string addr, string ph, string sk, Nullable<int> exp, string res, string photo, string st)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emParameter = em != null ?
                new ObjectParameter("em", em) :
                new ObjectParameter("em", typeof(string));
    
            var addrParameter = addr != null ?
                new ObjectParameter("addr", addr) :
                new ObjectParameter("addr", typeof(string));
    
            var phParameter = ph != null ?
                new ObjectParameter("ph", ph) :
                new ObjectParameter("ph", typeof(string));
    
            var skParameter = sk != null ?
                new ObjectParameter("sk", sk) :
                new ObjectParameter("sk", typeof(string));
    
            var expParameter = exp.HasValue ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(int));
    
            var resParameter = res != null ?
                new ObjectParameter("res", res) :
                new ObjectParameter("res", typeof(string));
    
            var photoParameter = photo != null ?
                new ObjectParameter("photo", photo) :
                new ObjectParameter("photo", typeof(string));
    
            var stParameter = st != null ?
                new ObjectParameter("st", st) :
                new ObjectParameter("st", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_registerUser", idParameter, nameParameter, emParameter, addrParameter, phParameter, skParameter, expParameter, resParameter, photoParameter, stParameter);
        }
    
        public virtual ObjectResult<sp_GetProject_Result> sp_GetProject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetProject_Result>("sp_GetProject");
        }
    
        public virtual int sp_InsertProject(string tit, string desc, string skil, Nullable<decimal> bud, Nullable<int> dur, Nullable<System.DateTime> deadline, Nullable<int> exp, string status)
        {
            var titParameter = tit != null ?
                new ObjectParameter("tit", tit) :
                new ObjectParameter("tit", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var skilParameter = skil != null ?
                new ObjectParameter("skil", skil) :
                new ObjectParameter("skil", typeof(string));
    
            var budParameter = bud.HasValue ?
                new ObjectParameter("bud", bud) :
                new ObjectParameter("bud", typeof(decimal));
    
            var durParameter = dur.HasValue ?
                new ObjectParameter("dur", dur) :
                new ObjectParameter("dur", typeof(int));
    
            var deadlineParameter = deadline.HasValue ?
                new ObjectParameter("deadline", deadline) :
                new ObjectParameter("deadline", typeof(System.DateTime));
    
            var expParameter = exp.HasValue ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertProject", titParameter, descParameter, skilParameter, budParameter, durParameter, deadlineParameter, expParameter, statusParameter);
        }
    
        public virtual int sp_editProject(Nullable<int> id, string desc, Nullable<decimal> budget, Nullable<int> dur, Nullable<System.DateTime> ded, string st)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var budgetParameter = budget.HasValue ?
                new ObjectParameter("budget", budget) :
                new ObjectParameter("budget", typeof(decimal));
    
            var durParameter = dur.HasValue ?
                new ObjectParameter("dur", dur) :
                new ObjectParameter("dur", typeof(int));
    
            var dedParameter = ded.HasValue ?
                new ObjectParameter("ded", ded) :
                new ObjectParameter("ded", typeof(System.DateTime));
    
            var stParameter = st != null ?
                new ObjectParameter("st", st) :
                new ObjectParameter("st", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_editProject", idParameter, descParameter, budgetParameter, durParameter, dedParameter, stParameter);
        }
    
        public virtual int sp_SearchProjects(string qry)
        {
            var qryParameter = qry != null ?
                new ObjectParameter("qry", qry) :
                new ObjectParameter("qry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SearchProjects", qryParameter);
        }
    
        public virtual int sp_BidProject(Nullable<int> prid, Nullable<int> userid, Nullable<decimal> amt, Nullable<int> days, string st)
        {
            var pridParameter = prid.HasValue ?
                new ObjectParameter("prid", prid) :
                new ObjectParameter("prid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var amtParameter = amt.HasValue ?
                new ObjectParameter("amt", amt) :
                new ObjectParameter("amt", typeof(decimal));
    
            var daysParameter = days.HasValue ?
                new ObjectParameter("days", days) :
                new ObjectParameter("days", typeof(int));
    
            var stParameter = st != null ?
                new ObjectParameter("st", st) :
                new ObjectParameter("st", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BidProject", pridParameter, useridParameter, amtParameter, daysParameter, stParameter);
        }
    
        public virtual ObjectResult<sp_GetProjectDetails_Result> sp_GetProjectDetails(Nullable<int> prid)
        {
            var pridParameter = prid.HasValue ?
                new ObjectParameter("prid", prid) :
                new ObjectParameter("prid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetProjectDetails_Result>("sp_GetProjectDetails", pridParameter);
        }
    
        public virtual ObjectResult<sp_GetProposals_Result> sp_GetProposals(Nullable<int> uid)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetProposals_Result>("sp_GetProposals", uidParameter);
        }
    
        public virtual ObjectResult<sp_GetProposalsByProjectId_Result> sp_GetProposalsByProjectId(Nullable<int> prid)
        {
            var pridParameter = prid.HasValue ?
                new ObjectParameter("prid", prid) :
                new ObjectParameter("prid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetProposalsByProjectId_Result>("sp_GetProposalsByProjectId", pridParameter);
        }
    }
}
