//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project2FreelancerPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_tab
    {
        public int projid { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string skills { get; set; }
        public decimal budget { get; set; }
        public int duration { get; set; }
        public System.DateTime deadline { get; set; }
        public int explevel { get; set; }
        public string projstatus { get; set; }
    }
}
