//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project2FreelancerPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class proposal
    {
        public int pid { get; set; }
        public int projid { get; set; }
        public int userid { get; set; }
        public decimal amount { get; set; }
        public int days { get; set; }
        public string pstatus { get; set; }
    }
}
